echo "CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;" >> initial.sql
echo "CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';" >> initial.sql
echo "GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_USER'@'%';" >> initial.sql
echo "FLUSH PRIVILEGES;" >> initial.sql
echo "ALTER USER 'root'@'localhost' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';" >> initial.sqlMYSQL_PASSWORD